#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Nov 02, 2023 02:54:28 PM -03  platform: Windows NT

import app_support
import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40'  # X11 color: #666666
_ana1color = '#c3c3c3'  # Closest X11 color: 'gray76'
_ana2color = 'beige'  # X11 color: #f5f5dc
_tabfg1 = 'black'
_tabfg2 = 'black'
_tabbg1 = 'grey75'
_tabbg2 = 'grey89'
_bgmode = 'light'


class Tela:

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1109x703+2352+164")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1,  1)
        top.title("Tela")
        top.configure(background="#a3a3a3")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.cvsTanque = tk.Canvas(self.top)
        self.cvsTanque.place(relx=0.505, rely=0.128,
                             relheight=0.841, relwidth=0.482)
        self.cvsTanque.configure(background="#868686")
        self.cvsTanque.configure(highlightbackground="#d9d9d9")
        self.cvsTanque.configure(highlightcolor="black")
        self.cvsTanque.configure(highlightthickness="0")
        self.cvsTanque.configure(insertbackground="black")
        self.cvsTanque.configure(relief="ridge")
        self.cvsTanque.configure(selectbackground="#c4c4c4")
        self.cvsTanque.configure(selectforeground="black")
        self.imgTanque = tk.Label(self.cvsTanque)
        self.imgTanque.place(relx=0.037, rely=0.118, height=508, width=496)
        self.imgTanque.configure(activebackground="#f9f9f9")
        self.imgTanque.configure(anchor='w')
        self.imgTanque.configure(background="#868686")
        self.imgTanque.configure(compound='left')
        self.imgTanque.configure(disabledforeground="#868686")
        self.imgTanque.configure(foreground="#ffffff")
        self.imgTanque.configure(highlightbackground="#d9d9d9")
        self.imgTanque.configure(highlightcolor="black")
        photo_location = os.path.join(_location, "./tanque.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.imgTanque.configure(image=_img0)
        self.lblValor = tk.Label(self.cvsTanque)
        self.lblValor.place(relx=0.40, rely=0.04, height=32, width=100)
        self.lblValor.configure(activebackground="#f9f9f9")
        self.lblValor.configure(anchor='w')
        self.lblValor.configure(background="#868686")
        self.lblValor.configure(borderwidth="0")
        self.lblValor.configure(compound='right')
        self.lblValor.configure(disabledforeground="#a3a3a3")
        self.lblValor.configure(font="-family {Arial} -size 20 -weight bold")
        self.lblValor.configure(foreground="#0000a0")
        self.lblValor.configure(highlightbackground="#d9d9d9")
        self.lblValor.configure(highlightcolor="black")
        self.lblValor.configure(justify='right')
        self.lblValor.configure(text='''0,00''')
        self.lblUnidade = tk.Label(self.cvsTanque)
        self.lblUnidade.place(relx=0.600, rely=0.034, height=31, width=35)
        self.lblUnidade.configure(activebackground="#f9f9f9")
        self.lblUnidade.configure(anchor='w')
        self.lblUnidade.configure(background="#868686")
        self.lblUnidade.configure(borderwidth="0")
        self.lblUnidade.configure(compound='left')
        self.lblUnidade.configure(disabledforeground="#a3a3a3")
        self.lblUnidade.configure(font="-family {Arial} -size 20 -weight bold")
        self.lblUnidade.configure(foreground="#0000a0")
        self.lblUnidade.configure(highlightbackground="#d9d9d9")
        self.lblUnidade.configure(highlightcolor="black")
        self.lblUnidade.configure(text='''m''')
        self.lblCubo = tk.Label(self.cvsTanque)
        self.lblCubo.place(relx=0.650, rely=0.0, height=41, width=25)
        self.lblCubo.configure(activebackground="#f9f9f9")
        self.lblCubo.configure(anchor='w')
        self.lblCubo.configure(background="#868686")
        self.lblCubo.configure(borderwidth="0")
        self.lblCubo.configure(compound='left')
        self.lblCubo.configure(disabledforeground="#a3a3a3")
        self.lblCubo.configure(font="-family {Arial} -size 20 -weight bold")
        self.lblCubo.configure(foreground="#0000a0")
        self.lblCubo.configure(highlightbackground="#d9d9d9")
        self.lblCubo.configure(highlightcolor="black")
        self.lblCubo.configure(text='''3''')
        self.lblVolume = tk.Label(self.cvsTanque)
        self.lblVolume.place(relx=0.15, rely=0.034, height=32, width=131)
        self.lblVolume.configure(activebackground="#f9f9f9")
        self.lblVolume.configure(anchor='w')
        self.lblVolume.configure(background="#868686")
        self.lblVolume.configure(borderwidth="0")
        self.lblVolume.configure(compound='left')
        self.lblVolume.configure(disabledforeground="#a3a3a3")
        self.lblVolume.configure(font="-family {Arial} -size 24 -weight bold")
        self.lblVolume.configure(foreground="#0000a0")
        self.lblVolume.configure(highlightbackground="#d9d9d9")
        self.lblVolume.configure(highlightcolor="black")
        self.lblVolume.configure(text='''Volume:''')
        self.cvsEntradas = tk.Canvas(self.top)
        self.cvsEntradas.place(relx=0.027, rely=0.354,
                               relheight=0.391, relwidth=0.454)
        self.cvsEntradas.configure(background="#868686")
        self.cvsEntradas.configure(closeenough="0.0")
        self.cvsEntradas.configure(highlightbackground="#d9d9d9")
        self.cvsEntradas.configure(highlightcolor="black")
        self.cvsEntradas.configure(highlightthickness="0")
        self.cvsEntradas.configure(insertbackground="black")
        self.cvsEntradas.configure(relief="ridge")
        self.cvsEntradas.configure(selectbackground="#c4c4c4")
        self.cvsEntradas.configure(selectforeground="black")
        self.lblAltura = tk.Label(self.cvsEntradas)
        self.lblAltura.place(relx=0.099, rely=0.167, height=29, width=164)
        self.lblAltura.configure(activebackground="#f9f9f9")
        self.lblAltura.configure(anchor='w')
        self.lblAltura.configure(background="#868686")
        self.lblAltura.configure(compound='left')
        self.lblAltura.configure(disabledforeground="#a3a3a3")
        self.lblAltura.configure(font="-family {Arial} -size 24")
        self.lblAltura.configure(foreground="#0000a0")
        self.lblAltura.configure(highlightbackground="#d9d9d9")
        self.lblAltura.configure(highlightcolor="black")
        self.lblAltura.configure(text='''Altura (m):''')
        self.txtAltura = tk.Entry(self.cvsEntradas)
        self.txtAltura.place(relx=0.537, rely=0.142, height=40, relwidth=0.326)
        self.txtAltura.configure(background="white")
        self.txtAltura.configure(disabledforeground="#a3a3a3")
        self.txtAltura.configure(font="-family {Arial} -size 24")
        self.txtAltura.configure(foreground="#000000")
        self.txtAltura.configure(highlightbackground="#d9d9d9")
        self.txtAltura.configure(highlightcolor="black")
        self.txtAltura.configure(insertbackground="black")
        self.txtAltura.configure(selectbackground="#c4c4c4")
        self.txtAltura.configure(selectforeground="black")
        self.lblDiametro = tk.Label(self.cvsEntradas)
        self.lblDiametro.place(relx=0.099, rely=0.389, height=29, width=204)
        self.lblDiametro.configure(activebackground="#f9f9f9")
        self.lblDiametro.configure(anchor='w')
        self.lblDiametro.configure(background="#868686")
        self.lblDiametro.configure(compound='left')
        self.lblDiametro.configure(disabledforeground="#a3a3a3")
        self.lblDiametro.configure(font="-family {Arial} -size 24")
        self.lblDiametro.configure(foreground="#0000a0")
        self.lblDiametro.configure(highlightbackground="#d9d9d9")
        self.lblDiametro.configure(highlightcolor="black")
        self.lblDiametro.configure(text='''Diâmetro (m):''')
        self.txtDiametro = tk.Entry(self.cvsEntradas)
        self.txtDiametro.place(relx=0.537, rely=0.389,
                               height=40, relwidth=0.326)
        self.txtDiametro.configure(background="white")
        self.txtDiametro.configure(disabledforeground="#a3a3a3")
        self.txtDiametro.configure(font="-family {Arial} -size 24")
        self.txtDiametro.configure(foreground="#000000")
        self.txtDiametro.configure(highlightbackground="#d9d9d9")
        self.txtDiametro.configure(highlightcolor="black")
        self.txtDiametro.configure(insertbackground="black")
        self.txtDiametro.configure(selectbackground="#c4c4c4")
        self.txtDiametro.configure(selectforeground="black")
        self.btnEnviar = tk.Button(self.cvsEntradas)
        self.btnEnviar.place(relx=0.358, rely=0.705, height=44, width=137)
        self.btnEnviar.configure(activebackground="beige")
        self.btnEnviar.configure(activeforeground="black")
        self.btnEnviar.configure(background="#b0b0b0")
        self.btnEnviar.configure(command=app_support.enviar)
        self.btnEnviar.configure(compound='center')
        self.btnEnviar.configure(disabledforeground="#a3a3a3")
        self.btnEnviar.configure(font="-family {Arial} -size 24")
        self.btnEnviar.configure(foreground="#0000a0")
        self.btnEnviar.configure(highlightbackground="#d9d9d9")
        self.btnEnviar.configure(highlightcolor="black")
        self.btnEnviar.configure(pady="0")
        self.btnEnviar.configure(text='''Enviar''')
        self.btnEnviar.configure(command=app_support.enviar)
        self.cvsTitulo = tk.Canvas(self.top)
        self.cvsTitulo.place(relx=0.027, rely=0.142,
                             relheight=0.095, relwidth=0.454)
        self.cvsTitulo.configure(background="#868686")
        self.cvsTitulo.configure(highlightbackground="#d9d9d9")
        self.cvsTitulo.configure(highlightcolor="black")
        self.cvsTitulo.configure(highlightthickness="0")
        self.cvsTitulo.configure(insertbackground="black")
        self.cvsTitulo.configure(relief="ridge")
        self.cvsTitulo.configure(selectbackground="#c4c4c4")
        self.cvsTitulo.configure(selectforeground="black")
        self.lblTitulo = tk.Label(self.cvsTitulo)
        self.lblTitulo.place(relx=0.02, rely=0.299, height=36, width=464)
        self.lblTitulo.configure(activebackground="#f9f9f9")
        self.lblTitulo.configure(anchor='w')
        self.lblTitulo.configure(background="#868686")
        self.lblTitulo.configure(borderwidth="0")
        self.lblTitulo.configure(compound='center')
        self.lblTitulo.configure(disabledforeground="#a3a3a3")
        self.lblTitulo.configure(font="-family {Arial} -size 24 -weight bold")
        self.lblTitulo.configure(foreground="#0000a0")
        self.lblTitulo.configure(highlightbackground="#d9d9d9")
        self.lblTitulo.configure(highlightcolor="black")
        self.lblTitulo.configure(text='''Cálculo de Volume do Tanque''')


def start_up():
    app_support.main()


if __name__ == '__main__':
    app_support.main()
